// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VroksNet.Infrastructure.Persistence;

#nullable disable

namespace VroksNet.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VroksNetDbContext))]
    [Migration("20261003165650_AddTestSuites")]
    partial class AddTestSuites
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("VroksNet.Domain.ApiSpecifications.ApiSpecification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ProvisionedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("ApiSpecifications");
                });

            modelBuilder.Entity("VroksNet.Domain.CallRecords.CallRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("ContractValid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("MockEndpointId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PublisherId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestLine")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SpecificationId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TestRunId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TestScenarioId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValidationErrors")
                        .HasColumnType("TEXT");

                    b.Property<string>("Warnings")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp", "Id");

                    b.HasIndex("SpecificationId", "Timestamp", "Id");

                    b.ToTable("CallRecords");
                });

            modelBuilder.Entity("VroksNet.Domain.Connections.Connection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ProvisionedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Connections");
                });

            modelBuilder.Entity("VroksNet.Domain.MockEndpoints.MockEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExampleStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExampleTemplate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperationKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestSchema")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseSchema")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseSchemasByStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ServeAtRealPath")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SpecificationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SpecificationId");

                    b.ToTable("MockEndpoints");
                });

            modelBuilder.Entity("VroksNet.Domain.Publishers.Publisher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Exchange")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastPublishMessage")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("LastPublishSuccess")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastPublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MockEndpointId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadOverride")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ProvisionedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SpecificationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("VroksNet.Domain.TestRuns.TestRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("ContractValid")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FinishedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<long>("ScheduledFor")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SuiteRunId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TestScenarioId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Trigger")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValidationErrors")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SuiteRunId");

                    b.HasIndex("Status", "ScheduledFor");

                    b.HasIndex("TestScenarioId", "ScheduledFor", "Id");

                    b.ToTable("TestRuns");
                });

            modelBuilder.Entity("VroksNet.Domain.TestScenarios.TestScenario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Exchange")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastRunAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastRunMessage")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("LastRunSuccess")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ListenTimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MockEndpointId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadOverride")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ProvisionedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Schedule")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScheduleTimeZone")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SpecificationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TestScenarios");
                });

            modelBuilder.Entity("VroksNet.Domain.TestSuites.SuiteRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("FinishedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<long>("ScheduledFor")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TestSuiteId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Trigger")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status", "ScheduledFor");

                    b.HasIndex("TestSuiteId", "ScheduledFor");

                    b.ToTable("SuiteRuns");
                });

            modelBuilder.Entity("VroksNet.Domain.TestSuites.TestSuite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TestScenarioIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TestSuites");
                });

            modelBuilder.Entity("VroksNet.Domain.MockEndpoints.MockEndpoint", b =>
                {
                    b.HasOne("VroksNet.Domain.ApiSpecifications.ApiSpecification", null)
                        .WithMany("Endpoints")
                        .HasForeignKey("SpecificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VroksNet.Domain.ApiSpecifications.ApiSpecification", b =>
                {
                    b.Navigation("Endpoints");
                });
#pragma warning restore 612, 618
        }
    }
}
